# Nombre del flujo de trabajo
name: Deploy Supabase Function

# Cuándo se ejecuta este flujo de trabajo
on:
  push:
    branches:
      - main  # Se ejecutará cada vez que hagas un push a la rama 'main'

# Los trabajos que se van a realizar
jobs:
  deploy-function:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código. Esto crea la estructura /home/runner/work/bibioapp/bibioapp/
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Le decimos que clone el contenido DENTRO de una subcarpeta llamada 'bibioapp'
          path: bibioapp

      # 2. Instalar la CLI de Supabase
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # 3. Despliega la función (¡AQUÍ ESTÁ LA MAGIA!)
      # Le decimos a este paso que se ejecute DESDE DENTRO de la subcarpeta 'bibioapp'
      - name: Deploy Edge Function
        working-directory: ./bibioapp
        run: |
          supabase functions deploy admin-user-manager --project-ref ihameevapgnfkzrlezjc --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}