# Nombre del flujo de trabajo
name: Deploy Supabase Function

# Cuándo se ejecuta este flujo de trabajo
on:
  push:
    branches:
      - main  # Se ejecutará cada vez que hagas un push a la rama 'main'

# Los trabajos que se van a realizar
jobs:
  deploy-function:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar la CLI de Supabase
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # 3. Despliega la función (¡AQUÍ ESTÁ EL CAMBIO!)
      # Le decimos explícitamente a la CLI dónde encontrar las funciones.
      - name: Deploy Edge Function
        run: |
          supabase functions deploy --functions-path ./supabase/functions admin-user-manager --project-ref ihameevapgnfkzrlezjc --no-verify-jwt
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}